// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pkixezdlbmzntwekchoq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBraXhlemRsYm16bnR3ZWtjaG9xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5MzU2NDcsImV4cCI6MjA3MTUxMTY0N30.wIzA1ULnhjmh8-hkERhbVnpvQzvnzJD_4J-3FxCw1K4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
  }
});

// Make supabase available globally for production debugging
if (typeof window !== 'undefined') {
  (window as any).supabase = supabase;
}